# https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

# [azure]
# disabled = false

# [character]
# # error_symbol = "[â¯](bold red)"
# error_symbol = "[ï‘®](bold red)"
[cmd_duration]
disabled = true

[directory]
# truncate_to_repo = false
use_os_path_sep = false
style = "yellow"


[git_branch]
# disabled = true
style ="green"
format = "[$symbol$branch(:$remote_branch) ]($style)"
only_attached = true
ignore_branches = ['_top-core-cbs']
symbol = "î‚ "

# [git_commit]
# disabled = true

# [git_state]
# disabled = true

[git_status]
disabled = true
# stashed = ""

[java]
disabled = true
format ="[$symbol($version )]($style)"
version_format = "v${major}"
style = 'red'
symbol = "îœ¸"

[nodejs]
disabled = true
format = "[$symbol($version )]($style)"
style ="green"
symbol = "îœ˜"

[python]
disabled = true
version_format = "v${major}.${minor}"
format = "[$symbol($version )]($style)"

[scala]
disabled = true

[vagrant]
format = "[$symbol($version )]($style)"

[package]
disabled = true
format="[$symbol$version]($style)"
symbol = "ğŸ“¦"

[gradle]
format="[$symbol($version )]($style)"
